import type { Metadata } from "next";
import { LeaguaOfLegendLayout } from "~pages/league/ui";

export const metadata: Metadata = {
  title: "League of Legends STATS",
  description: "Generated by create next app",
};

export default function LeaguaOfLegend() {
  return <LeaguaOfLegendLayout />;
}
