import type { Metadata } from "next";
import { PubgLayout } from "~pages/pubg";

export const metadata: Metadata = {
  title: "PUBG STATS",
  description: "Generated by create next app",
};

export default function Home() {
  return <PubgLayout />;
}
